In [1]:
#  STEP 1: Imports
import pandas as pd
import json
from datetime import datetime
import os

#  STEP 2: CSV Log File Path
csv_path = "rlhf_feedback_log.csv"

#  STEP 3: Function to Collect Feedback for One Query
def collect_feedback_for_query(query, fallback_answer, direct_answer, variant_answer):
    print("\n📌 Compare Responses:\n")
    print("TinyLLaMA:\n", fallback_answer)
    print("\nDirect:\n", direct_answer)
    print("\nVariant:\n", variant_answer)

    selected_best = input("\n🧠 Which answer was best? (TinyLLaMA / Direct / Variant): ").strip()

    # Prepare log entry
    log_entry = {
        "timestamp": datetime.now().isoformat(),
        "query": query,
        "responses": json.dumps({
            "TinyLLaMA": fallback_answer,
            "Direct": direct_answer,
            "Variant": variant_answer
        }),
        "selected_best": selected_best
    }

    # Save to CSV
    df_log = pd.DataFrame([log_entry])
    df_log.to_csv(csv_path, mode='a', header=not os.path.exists(csv_path), index=False)
    print(f"\n Feedback saved successfully for query: '{query}'")

#  STEP 4: 10 Diverse Examples to Label
examples = [
    {
        "query": "What is AI?",
        "TinyLLaMA": "AI is like a machine brain that learns from data.",
        "Direct": "Artificial Intelligence allows machines to mimic human behavior.",
        "Variant": "AI refers to machines simulating intelligent actions."
    },
    {
        "query": "What is quantum computing?",
        "TinyLLaMA": "Quantum computing uses quantum bits to process data differently than classical computers.",
        "Direct": "Quantum computers use superposition and entanglement to solve complex problems.",
        "Variant": "It’s a computing approach that explores quantum mechanics for faster solutions."
    },
    {
        "query": "Explain machine learning.",
        "TinyLLaMA": "Machine learning allows computers to improve performance from experience.",
        "Direct": "ML is a subfield of AI that trains models using data.",
        "Variant": "It's a way to program computers to learn patterns automatically."
    },
    {
        "query": "Define deep learning.",
        "TinyLLaMA": "Deep learning is a type of machine learning using many layers.",
        "Direct": "It’s based on neural networks with multiple layers for feature learning.",
        "Variant": "Deep learning mimics the brain using deep neural networks to understand data."
    },
    {
        "query": "What is reinforcement learning?",
        "TinyLLaMA": "RL is about learning by trial and error using rewards.",
        "Direct": "It’s a type of ML where agents learn from actions and consequences.",
        "Variant": "Reinforcement learning optimizes behavior through rewards and penalties."
    },
    {
        "query": "What is NLP?",
        "TinyLLaMA": "NLP helps computers understand human language.",
        "Direct": "Natural Language Processing is used in chatbots, translators, and sentiment analysis.",
        "Variant": "It enables interaction between machines and humans using text or speech."
    },
    {
        "query": "What is a neural network?",
        "TinyLLaMA": "Neural networks are algorithms inspired by how the brain works.",
        "Direct": "They consist of layers that transform input into useful predictions.",
        "Variant": "Neural networks connect nodes to recognize patterns in data."
    },
    {
        "query": "What is supervised learning?",
        "TinyLLaMA": "Supervised learning trains on labeled data to make predictions.",
        "Direct": "It means using inputs and known outputs to train models.",
        "Variant": "Models learn from examples where the answer is already provided."
    },
    {
        "query": "Explain unsupervised learning.",
        "TinyLLaMA": "Unsupervised learning finds hidden patterns without labeled data.",
        "Direct": "It's about grouping or reducing data without knowing the output.",
        "Variant": "Unsupervised models explore structure in data without guidance."
    },
    {
        "query": "What is a chatbot?",
        "TinyLLaMA": "A chatbot is a computer program that talks to humans.",
        "Direct": "Chatbots simulate conversations and answer user questions.",
        "Variant": "They are AI tools that respond using natural language."
    }
]

#  STEP 5: Loop to Collect Feedback
for ex in examples:
    collect_feedback_for_query(ex["query"], ex["TinyLLaMA"], ex["Direct"], ex["Variant"])

#  STEP 6: View Collected Feedback (Optional)
df = pd.read_csv(csv_path)
print("\n📝 Logged Feedback Preview:")
display(df.tail(10))

📌 Compare Responses:

TinyLLaMA:
 AI is like a machine brain that learns from data.

Direct:
 Artificial Intelligence allows machines to mimic human behavior.

Variant:
 AI refers to machines simulating intelligent actions.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  direct

 Feedback saved successfully for query: 'What is AI?'

📌 Compare Responses:

TinyLLaMA:
 Quantum computing uses quantum bits to process data differently than classical computers.

Direct:
 Quantum computers use superposition and entanglement to solve complex problems.

Variant:
 It’s a computing approach that explores quantum mechanics for faster solutions.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  tinyllama

 Feedback saved successfully for query: 'What is quantum computing?'

📌 Compare Responses:

TinyLLaMA:
 Machine learning allows computers to improve performance from experience.

Direct:
 ML is a subfield of AI that trains models using data.

Variant:
 It's a way to program computers to learn patterns automatically.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  tinyllama

 Feedback saved successfully for query: 'Explain machine learning.'

📌 Compare Responses:

TinyLLaMA:
 Deep learning is a type of machine learning using many layers.

Direct:
 It’s based on neural networks with multiple layers for feature learning.

Variant:
 Deep learning mimics the brain using deep neural networks to understand data.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  direct

 Feedback saved successfully for query: 'Define deep learning.'

📌 Compare Responses:

TinyLLaMA:
 RL is about learning by trial and error using rewards.

Direct:
 It’s a type of ML where agents learn from actions and consequences.

Variant:
 Reinforcement learning optimizes behavior through rewards and penalties.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  tinylamma

 Feedback saved successfully for query: 'What is reinforcement learning?'

📌 Compare Responses:

TinyLLaMA:
 NLP helps computers understand human language.

Direct:
 Natural Language Processing is used in chatbots, translators, and sentiment analysis.

Variant:
 It enables interaction between machines and humans using text or speech.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  direct

 Feedback saved successfully for query: 'What is NLP?'

📌 Compare Responses:

TinyLLaMA:
 Neural networks are algorithms inspired by how the brain works.

Direct:
 They consist of layers that transform input into useful predictions.

Variant:
 Neural networks connect nodes to recognize patterns in data.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  tinyllama

 Feedback saved successfully for query: 'What is a neural network?'

📌 Compare Responses:

TinyLLaMA:
 Supervised learning trains on labeled data to make predictions.

Direct:
 It means using inputs and known outputs to train models.

Variant:
 Models learn from examples where the answer is already provided.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  variant

 Feedback saved successfully for query: 'What is supervised learning?'

📌 Compare Responses:

TinyLLaMA:
 Unsupervised learning finds hidden patterns without labeled data.

Direct:
 It's about grouping or reducing data without knowing the output.

Variant:
 Unsupervised models explore structure in data without guidance.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  variant

 Feedback saved successfully for query: 'Explain unsupervised learning.'

📌 Compare Responses:

TinyLLaMA:
 A chatbot is a computer program that talks to humans.

Direct:
 Chatbots simulate conversations and answer user questions.

Variant:
 They are AI tools that respond using natural language.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  variant

 Feedback saved successfully for query: 'What is a chatbot?'

📝 Logged Feedback Preview:

,timestamp,query,responses,selected_best
59,2025-07-13T12:20:02.389818,What is AI?,"{""TinyLLaMA"": ""AI is like a machine brain that...",direct
60,2025-07-13T12:20:06.774414,What is quantum computing?,"{""TinyLLaMA"": ""Quantum computing uses quantum ...",tinyllama
61,2025-07-13T12:20:14.017940,Explain machine learning.,"{""TinyLLaMA"": ""Machine learning allows compute...",tinyllama
62,2025-07-13T12:20:17.554011,Define deep learning.,"{""TinyLLaMA"": ""Deep learning is a type of mach...",direct
63,2025-07-13T12:20:21.954568,What is reinforcement learning?,"{""TinyLLaMA"": ""RL is about learning by trial a...",tinylamma
64,2025-07-13T12:21:33.299003,What is NLP?,"{""TinyLLaMA"": ""NLP helps computers understand ...",direct
65,2025-07-13T12:21:38.749676,What is a neural network?,"{""TinyLLaMA"": ""Neural networks are algorithms ...",tinyllama
66,2025-07-13T12:21:42.693695,What is supervised learning?,"{""TinyLLaMA"": ""Supervised learning trains on l...",variant
67,2025-07-13T12:21:47.109281,Explain unsupervised learning.,"{""TinyLLaMA"": ""Unsupervised learning finds hid...",variant
68,2025-07-13T12:21:52.713015,What is a chatbot?,"{""TinyLLaMA"": ""A chatbot is a computer program...",variant

In [2]:
example_queries = [
    "What is AI?", "Define NLP.", "Explain supervised learning.",
    "What is reinforcement learning?", "Define a chatbot.",
    "What is quantum computing?", "Explain deep learning.",
    "What is a neural network?", "What is machine learning?"
]

for ex in example_queries:
    fallback_answer = "TinyLLaMA: Answer for " + ex
    direct_answer = "Direct: Answer for " + ex
    variant_answer = "Variant: Answer for " + ex
    collect_feedback_for_query(ex, fallback_answer, direct_answer, variant_answer)

📌 Compare Responses:

TinyLLaMA:
 TinyLLaMA: Answer for What is AI?

Direct:
 Direct: Answer for What is AI?

Variant:
 Variant: Answer for What is AI?

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  direct

 Feedback saved successfully for query: 'What is AI?'

📌 Compare Responses:

TinyLLaMA:
 TinyLLaMA: Answer for Define NLP.

Direct:
 Direct: Answer for Define NLP.

Variant:
 Variant: Answer for Define NLP.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  variant

 Feedback saved successfully for query: 'Define NLP.'

📌 Compare Responses:

TinyLLaMA:
 TinyLLaMA: Answer for Explain supervised learning.

Direct:
 Direct: Answer for Explain supervised learning.

Variant:
 Variant: Answer for Explain supervised learning.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  direct

 Feedback saved successfully for query: 'Explain supervised learning.'

📌 Compare Responses:

TinyLLaMA:
 TinyLLaMA: Answer for What is reinforcement learning?

Direct:
 Direct: Answer for What is reinforcement learning?

Variant:
 Variant: Answer for What is reinforcement learning?

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  tinyllama'

 Feedback saved successfully for query: 'What is reinforcement learning?'

📌 Compare Responses:

TinyLLaMA:
 TinyLLaMA: Answer for Define a chatbot.

Direct:
 Direct: Answer for Define a chatbot.

Variant:
 Variant: Answer for Define a chatbot.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  direct

 Feedback saved successfully for query: 'Define a chatbot.'

📌 Compare Responses:

TinyLLaMA:
 TinyLLaMA: Answer for What is quantum computing?

Direct:
 Direct: Answer for What is quantum computing?

Variant:
 Variant: Answer for What is quantum computing?

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  tinyllama

 Feedback saved successfully for query: 'What is quantum computing?'

📌 Compare Responses:

TinyLLaMA:
 TinyLLaMA: Answer for Explain deep learning.

Direct:
 Direct: Answer for Explain deep learning.

Variant:
 Variant: Answer for Explain deep learning.

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  direct

 Feedback saved successfully for query: 'Explain deep learning.'

📌 Compare Responses:

TinyLLaMA:
 TinyLLaMA: Answer for What is a neural network?

Direct:
 Direct: Answer for What is a neural network?

Variant:
 Variant: Answer for What is a neural network?

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  direct

 Feedback saved successfully for query: 'What is a neural network?'

📌 Compare Responses:

TinyLLaMA:
 TinyLLaMA: Answer for What is machine learning?

Direct:
 Direct: Answer for What is machine learning?

Variant:
 Variant: Answer for What is machine learning?

🧠 Which answer was best? (TinyLLaMA / Direct / Variant):  tinyllama

 Feedback saved successfully for query: 'What is machine learning?'

In [3]:
# Step 1: Imports
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import joblib
import ast

# Step 2: Load feedback
df = pd.read_csv("rlhf_feedback_log.csv")

# Step 3: Prepare Data
texts = []
labels = []

for i, row in df.iterrows():
    try:
        response_dict = ast.literal_eval(row["responses"])
        selected = row["selected_best"].strip().lower()

        if selected not in ["tinyllama", "direct", "variant"]:
            continue

        combined_text = (
            "TinyLLaMA: " + response_dict.get("TinyLLaMA", "") + "\n" +
            "Direct: " + response_dict.get("Direct", "") + "\n" +
            "Variant: " + response_dict.get("Variant", "")
        )

        texts.append(combined_text)
        labels.append(selected)
    except:
        continue

# Step 4: TF-IDF
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)

# Step 5: Train model
model = LogisticRegression()
model.fit(X, labels)

# Step 6: Save model and vectorizer
joblib.dump(model, "reward_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print("✅ Reward model and vectorizer saved successfully!")

✅ Reward model and vectorizer saved successfully!

In [4]:
import joblib

# Load correct model
model = joblib.load("reward_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

# Example input
text_input = """TinyLLaMA: AI is a machine brain
Direct: AI mimics human behavior
Variant: AI simulates intelligent action"""

X = vectorizer.transform([text_input])
predicted_label = model.predict(X)[0]

print("✅ Predicted Best Answer:", predicted_label)

✅ Predicted Best Answer: direct

In [4]:
pip install trl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: trl in c:\users\manjo\appdata\roaming\python\python312\site-packages (0.4.7)
Requirement already satisfied: torch>=1.4.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from trl) (2.7.0)
Requirement already satisfied: transformers>=4.18.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from trl) (4.51.3)
Requirement already satisfied: numpy>=1.18.2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from trl) (1.26.4)
Requirement already satisfied: accelerate in c:\users\manjo\appdata\roaming\python\python312\site-packages (from trl) (1.7.0)
Requirement already satisfied: datasets in c:\users\manjo\appdata\roaming\python\python312\site-packages (from trl) (3.6.0)
Requirement already satisfied: filelock in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=1.4.0->trl) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=1.4.0->trl) (4.13.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=1.4.0->trl) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=1.4.0->trl) (3.1.4)
Requirement already satisfied: fsspec in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=1.4.0->trl) (2025.3.0)
Requirement already satisfied: setuptools in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=1.4.0->trl) (70.1.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers>=4.18.0->trl) (0.31.2)
Requirement already satisfied: packaging>=20.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers>=4.18.0->trl) (24.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers>=4.18.0->trl) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers>=4.18.0->trl) (2024.11.6)
Requirement already satisfied: requests in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers>=4.18.0->trl) (2.32.2)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers>=4.18.0->trl) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers>=4.18.0->trl) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers>=4.18.0->trl) (4.67.1)
Requirement already satisfied: psutil in c:\users\manjo\appdata\roaming\python\python312\site-packages (from accelerate->trl) (5.9.8)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets->trl) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets->trl) (0.3.8)
Requirement already satisfied: pandas in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets->trl) (2.2.2)
Requirement already satisfied: xxhash in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets->trl) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets->trl) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl) (3.11.18)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from requests->transformers>=4.18.0->trl) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from requests->transformers>=4.18.0->trl) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from requests->transformers>=4.18.0->trl) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from requests->transformers>=4.18.0->trl) (2024.2.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from sympy>=1.13.3->torch>=1.4.0->trl) (1.3.0)
Requirement already satisfied: colorama in c:\users\manjo\appdata\roaming\python\python312\site-packages (from tqdm>=4.27->transformers>=4.18.0->trl) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from jinja2->torch>=1.4.0->trl) (2.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from pandas->datasets->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from pandas->datasets->trl) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from pandas->datasets->trl) (2024.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl) (1.20.0)
Requirement already satisfied: six>=1.5 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas->datasets->trl) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.1.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import joblib

In [6]:
#  Step: Simulated PPO Loop using reward model
import joblib
import random

# Load your saved reward model and vectorizer
reward_model = joblib.load("reward_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

# Sample query and candidate responses
query = "What is AI?"
candidates = [
    "AI is like a machine brain that learns from data.",
    "AI allows machines to mimic human behavior.",
    "AI refers to computers making intelligent decisions."
]

# Evaluate each candidate
X = vectorizer.transform(candidates)
probs = reward_model.predict_proba(X)[:, 1]  # Probability of being the best
best_index = probs.argmax()
best_response = candidates[best_index]

# Print output
print(f"\n Query: {query}")
for i, (text, prob) in enumerate(zip(candidates, probs)):
    print(f"\nResponse {i+1}: {text}\nReward: {prob:.4f}")

print(f"\n Selected Best Response: {best_response}")

 Query: What is AI?

Response 1: AI is like a machine brain that learns from data.
Reward: 0.1979

Response 2: AI allows machines to mimic human behavior.
Reward: 0.1713

Response 3: AI refers to computers making intelligent decisions.
Reward: 0.2402

 Selected Best Response: AI refers to computers making intelligent decisions.

In [7]:
#pip install transformers accelerate trl datasets

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in c:\users\manjo\appdata\roaming\python\python312\site-packages (4.51.3)
Requirement already satisfied: accelerate in c:\users\manjo\appdata\roaming\python\python312\site-packages (1.7.0)
Requirement already satisfied: trl in c:\users\manjo\appdata\roaming\python\python312\site-packages (0.4.7)
Requirement already satisfied: datasets in c:\users\manjo\appdata\roaming\python\python312\site-packages (3.6.0)
Requirement already satisfied: filelock in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers) (0.31.2)
Requirement already satisfied: numpy>=1.17 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers) (24.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers) (2.32.2)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers) (4.67.1)
Requirement already satisfied: psutil in c:\users\manjo\appdata\roaming\python\python312\site-packages (from accelerate) (5.9.8)
Requirement already satisfied: torch>=2.0.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from accelerate) (2.7.0)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.11.18)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from requests->transformers) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from requests->transformers) (2024.2.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=2.0.0->accelerate) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=2.0.0->accelerate) (3.1.4)
Requirement already satisfied: setuptools in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=2.0.0->accelerate) (70.1.0)
Requirement already satisfied: colorama in c:\users\manjo\appdata\roaming\python\python312\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.20.0)
Requirement already satisfied: six>=1.5 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from jinja2->torch>=2.0.0->accelerate) (2.1.5)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.1.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
#!pip install -U trl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: trl in c:\users\manjo\appdata\roaming\python\python312\site-packages (0.17.0)
Collecting trl
  Downloading trl-0.19.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: accelerate>=1.4.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from trl) (1.7.0)
Requirement already satisfied: datasets>=3.0.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from trl) (3.6.0)
Requirement already satisfied: transformers>=4.51.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from trl) (4.51.3)
Requirement already satisfied: numpy<3.0.0,>=1.17 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from accelerate>=1.4.0->trl) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from accelerate>=1.4.0->trl) (24.0)
Requirement already satisfied: psutil in c:\users\manjo\appdata\roaming\python\python312\site-packages (from accelerate>=1.4.0->trl) (5.9.8)
Requirement already satisfied: pyyaml in c:\users\manjo\appdata\roaming\python\python312\site-packages (from accelerate>=1.4.0->trl) (6.0.2)
Requirement already satisfied: torch>=2.0.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from accelerate>=1.4.0->trl) (2.7.0)
Requirement already satisfied: huggingface-hub>=0.21.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from accelerate>=1.4.0->trl) (0.31.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from accelerate>=1.4.0->trl) (0.5.3)
Requirement already satisfied: filelock in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets>=3.0.0->trl) (3.18.0)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets>=3.0.0->trl) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets>=3.0.0->trl) (0.3.8)
Requirement already satisfied: pandas in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets>=3.0.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets>=3.0.0->trl) (2.32.2)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets>=3.0.0->trl) (4.67.1)
Requirement already satisfied: xxhash in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets>=3.0.0->trl) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from datasets>=3.0.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (2025.3.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers>=4.51.0->trl) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from transformers>=4.51.0->trl) (0.21.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (3.11.18)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from huggingface-hub>=0.21.0->accelerate>=1.4.0->trl) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (2024.2.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.1.4)
Requirement already satisfied: setuptools in c:\users\manjo\appdata\roaming\python\python312\site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (70.1.0)
Requirement already satisfied: colorama in c:\users\manjo\appdata\roaming\python\python312\site-packages (from tqdm>=4.66.3->datasets>=3.0.0->trl) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from pandas->datasets>=3.0.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from pandas->datasets>=3.0.0->trl) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from pandas->datasets>=3.0.0->trl) (2024.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=3.0.0->trl) (1.20.0)
Requirement already satisfied: six>=1.5 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas->datasets>=3.0.0->trl) (1.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\manjo\appdata\roaming\python\python312\site-packages (from jinja2->torch>=2.0.0->accelerate>=1.4.0->trl) (2.1.5)
Downloading trl-0.19.1-py3-none-any.whl (376 kB)
   ---------------------------------------- 0.0/376.2 kB ? eta -:--:--
   ---------------------------------------  368.6/376.2 kB 7.6 MB/s eta 0:00:01
   ---------------------------------------- 376.2/376.2 kB 5.9 MB/s eta 0:00:00
Installing collected packages: trl
  Attempting uninstall: trl
    Found existing installation: trl 0.17.0
    Uninstalling trl-0.17.0:
      Successfully uninstalled trl-0.17.0
Successfully installed trl-0.19.1

  WARNING: The script trl.exe is installed in 'C:\Users\manjo\AppData\Roaming\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.1.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
#!pip install trl==0.4.7 --upgrade --quiet

[notice] A new release of pip is available: 24.1.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
#  Step: Simulated PPO Loop using reward model
import joblib
import random

# Load your saved reward model and vectorizer
reward_model = joblib.load("reward_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

# Sample query and candidate responses
query = "What is AI?"
candidates = [
    "AI is like a machine brain that learns from data.",
    "AI allows machines to mimic human behavior.",
    "AI refers to computers making intelligent decisions."
]

# Evaluate each candidate
X = vectorizer.transform(candidates)
probs = reward_model.predict_proba(X)[:, 1]  # Probability of being the best
best_index = probs.argmax()
best_response = candidates[best_index]

# Print output
print(f"\n Query: {query}")
for i, (text, prob) in enumerate(zip(candidates, probs)):
    print(f"\nResponse {i+1}: {text}\nReward: {prob:.4f}")

print(f"\n Selected Best Response: {best_response}")

,Query,Best Source,Best Response,TinyLLaMA Score,Direct Score,Variant Score
0,What is quantum computing?,Variant,Quantum computing uses quantum bits and is mor...,0.4097,0.4340,0.4407
1,what is AI?,Variant,Variant: what is AI? is answered with alternat...,0.1398,0.1454,0.1559
2,What is AI?,TinyLLaMA,AI is like a machine brain that learns from data.,0.1979,0.1882,0.1572
3,What is quantum computing?,TinyLLaMA,Quantum computing uses quantum bits to process...,0.4360,0.2927,0.3512
4,Explain machine learning.,Variant,It's a way to program computers to learn patte...,0.3857,0.3045,0.3944

In [10]:
#  Step: Simulated PPO Loop using reward model
import joblib
import random

# Load your saved reward model and vectorizer
reward_model = joblib.load("reward_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

# Sample query and candidate responses
query = "What is AI?"
candidates = [
    "AI is like a machine brain that learns from data.",
    "AI allows machines to mimic human behavior.",
    "AI refers to computers making intelligent decisions."
]

# Evaluate each candidate
X = vectorizer.transform(candidates)
probs = reward_model.predict_proba(X)[:, 1]  # Probability of being the best
best_index = probs.argmax()
best_response = candidates[best_index]

# Print output
print(f"\n Query: {query}")
for i, (text, prob) in enumerate(zip(candidates, probs)):
    print(f"\nResponse {i+1}: {text}\nReward: {prob:.4f}")

print(f"\n Selected Best Response: {best_response}")

🎯 Reward Model Accuracy: 0.5256410256410257

In [1]:
import numpy as np

# Softmax function to normalize rewards
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

In [ ]:
import joblib
import random
import json

# Load reward model and vectorizer
reward_model = joblib.load("reward_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

# Sample queries and a pool of candidates
queries = [
    "What is AI?", "What is NLP?", "Define chatbot.",
    "Explain supervised learning.", "What is deep learning?"
]

candidate_pool = [
    "AI allows machines to mimic human behavior.",
    "AI is like a machine brain that learns from data.",
    "AI refers to computers making intelligent decisions."
]

# Empty reward log
reward_log = []

# Simulate multiple queries
for query in queries:
    # Randomly choose 3 candidates per query
    sampled_candidates = random.sample(candidate_pool, 3)

    # Vectorize the candidates
    X = vectorizer.transform(sampled_candidates)

    # Predict reward scores (probability of best label)
    raw_rewards = reward_model.predict_proba(X)[:, 1]

    # Normalize rewards using softmax
    normalized_rewards = softmax(raw_rewards)

    print(f"\n🔍 Query: {query}")
    for i, (resp, score) in enumerate(zip(sampled_candidates, normalized_rewards)):
        print(f"\nResponse {i+1}: {resp}\nNormalized Reward: {score:.4f}")

        # Save to log
        reward_log.append({
            "query": query,
            "response": resp,
            "reward": float(score)
        })

# Save reward log as JSON
with open("simulated_reward_log.json", "w") as f:
    json.dump(reward_log, f, indent=2)

print("\n✅ Simulated reward log saved to 'simulated_reward_log.json'")

🔍 Query: What is AI?

Response 1: AI refers to computers making intelligent decisions.
Normalized Reward: 0.3458

Response 2: AI allows machines to mimic human behavior.
Normalized Reward: 0.3228

Response 3: AI is like a machine brain that learns from data.
Normalized Reward: 0.3315

🔍 Query: What is NLP?

Response 1: AI allows machines to mimic human behavior.
Normalized Reward: 0.3228

Response 2: AI refers to computers making intelligent decisions.
Normalized Reward: 0.3458

Response 3: AI is like a machine brain that learns from data.
Normalized Reward: 0.3315

🔍 Query: Define chatbot.

Response 1: AI is like a machine brain that learns from data.
Normalized Reward: 0.3315

Response 2: AI refers to computers making intelligent decisions.
Normalized Reward: 0.3458

Response 3: AI allows machines to mimic human behavior.
Normalized Reward: 0.3228

🔍 Query: Explain supervised learning.

Response 1: AI refers to computers making intelligent decisions.
Normalized Reward: 0.3458

Response 2: AI allows machines to mimic human behavior.
Normalized Reward: 0.3228

Response 3: AI is like a machine brain that learns from data.
Normalized Reward: 0.3315

🔍 Query: What is deep learning?

Response 1: AI allows machines to mimic human behavior.
Normalized Reward: 0.3228

Response 2: AI is like a machine brain that learns from data.
Normalized Reward: 0.3315

Response 3: AI refers to computers making intelligent decisions.
Normalized Reward: 0.3458

✅ Simulated reward log saved to 'simulated_reward_log.json'

C:\Users\manjo\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:440: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.5.2 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\manjo\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:440: InconsistentVersionWarning: Trying to unpickle estimator TfidfTransformer from version 1.5.2 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\manjo\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:440: InconsistentVersionWarning: Trying to unpickle estimator TfidfVectorizer from version 1.5.2 when using version 1.7.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(